/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "../utils/scaffold-eth/contract";

const deployedContracts = {
  1337: {
    MockLSP7: {
      address: "0xA6963Bf71beF054F3D510F138dE655FB47D59cF0",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
            {
              internalType: "string",
              name: "_symbol",
              type: "string",
            },
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "ERC725Y_DataKeysValuesEmptyArray",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC725Y_DataKeysValuesLengthMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC725Y_MsgValueDisallowed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "storedData",
              type: "bytes",
            },
          ],
          name: "InvalidExtensionAddress",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "InvalidFunctionSelector",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP4TokenNameNotEditable",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP4TokenSymbolNotEditable",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP4TokenTypeNotEditable",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "authorizedAmount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "LSP7AmountExceedsAuthorizedAmount",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "LSP7AmountExceedsBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "callIndex",
              type: "uint256",
            },
          ],
          name: "LSP7BatchCallFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP7CannotSendWithAddressZero",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP7CannotUseAddressZeroAsOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "LSP7DecreaseAllowanceNotAuthorized",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP7DecreasedAllowanceBelowZero",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP7InvalidTransferBatch",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenReceiver",
              type: "address",
            },
          ],
          name: "LSP7NotifyTokenReceiverContractMissingLSP1Interface",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenReceiver",
              type: "address",
            },
          ],
          name: "LSP7NotifyTokenReceiverIsEOA",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "LSP7RevokeOperatorNotAuthorized",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP7TokenContractCannotHoldValue",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP7TokenOwnerCannotBeOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "functionSelector",
              type: "bytes4",
            },
          ],
          name: "NoExtensionFoundForFunctionSelector",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "OperatorAllowanceCannotBeIncreasedFromZero",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "callerAddress",
              type: "address",
            },
          ],
          name: "OwnableCallerNotTheOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "OwnableCannotSetZeroAddressAsOwner",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          name: "DataChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "OperatorAuthorizationChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bool",
              name: "notified",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "OperatorRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "force",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          stateMutability: "payable",
          type: "fallback",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "authorizeOperator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
          ],
          name: "authorizedAmountFor",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes[]",
              name: "data",
              type: "bytes[]",
            },
          ],
          name: "batchCalls",
          outputs: [
            {
              internalType: "bytes[]",
              name: "results",
              type: "bytes[]",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "subtractedAmount",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "decreaseAllowance",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
          ],
          name: "getData",
          outputs: [
            {
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "dataKeys",
              type: "bytes32[]",
            },
          ],
          name: "getDataBatch",
          outputs: [
            {
              internalType: "bytes[]",
              name: "dataValues",
              type: "bytes[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
          ],
          name: "getOperatorsOf",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "addedAmount",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "increaseAllowance",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              internalType: "bool",
              name: "notify",
              type: "bool",
            },
            {
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "revokeOperator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          name: "setData",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "dataKeys",
              type: "bytes32[]",
            },
            {
              internalType: "bytes[]",
              name: "dataValues",
              type: "bytes[]",
            },
          ],
          name: "setDataBatch",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "force",
              type: "bool",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "transfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "from",
              type: "address[]",
            },
            {
              internalType: "address[]",
              name: "to",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "amount",
              type: "uint256[]",
            },
            {
              internalType: "bool[]",
              name: "force",
              type: "bool[]",
            },
            {
              internalType: "bytes[]",
              name: "data",
              type: "bytes[]",
            },
          ],
          name: "transferBatch",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
    MockLSP8: {
      address: "0x570DA9f60Bd214BcAe427868a137A29d2483379e",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
            {
              internalType: "string",
              name: "_symbol",
              type: "string",
            },
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "ERC725Y_DataKeysValuesEmptyArray",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC725Y_DataKeysValuesLengthMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC725Y_MsgValueDisallowed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "storedData",
              type: "bytes",
            },
          ],
          name: "InvalidExtensionAddress",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "InvalidFunctionSelector",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP4TokenNameNotEditable",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP4TokenSymbolNotEditable",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP4TokenTypeNotEditable",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "callIndex",
              type: "uint256",
            },
          ],
          name: "LSP8BatchCallFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8CannotSendToAddressZero",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8CannotUseAddressZeroAsOperator",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8InvalidTransferBatch",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8NonExistentTokenId",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8NonExistingOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "LSP8NotTokenOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "LSP8NotTokenOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenReceiver",
              type: "address",
            },
          ],
          name: "LSP8NotifyTokenReceiverContractMissingLSP1Interface",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenReceiver",
              type: "address",
            },
          ],
          name: "LSP8NotifyTokenReceiverIsEOA",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8OperatorAlreadyAuthorized",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8RevokeOperatorNotAuthorized",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenContractCannotHoldValue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8TokenIdAlreadyMinted",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenIdFormatNotEditable",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenIdsDataEmptyArray",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenIdsDataLengthMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenOwnerCannotBeOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "oldOwner",
              type: "address",
            },
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "LSP8TokenOwnerChanged",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "functionSelector",
              type: "bytes4",
            },
          ],
          name: "NoExtensionFoundForFunctionSelector",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "callerAddress",
              type: "address",
            },
          ],
          name: "OwnableCallerNotTheOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "OwnableCannotSetZeroAddressAsOwner",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          name: "DataChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "OperatorAuthorizationChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "notified",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "OperatorRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          name: "TokenIdDataChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "force",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          stateMutability: "payable",
          type: "fallback",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "authorizeOperator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes[]",
              name: "data",
              type: "bytes[]",
            },
          ],
          name: "batchCalls",
          outputs: [
            {
              internalType: "bytes[]",
              name: "results",
              type: "bytes[]",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
          ],
          name: "getData",
          outputs: [
            {
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "dataKeys",
              type: "bytes32[]",
            },
          ],
          name: "getDataBatch",
          outputs: [
            {
              internalType: "bytes[]",
              name: "dataValues",
              type: "bytes[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "tokenIds",
              type: "bytes32[]",
            },
            {
              internalType: "bytes32[]",
              name: "dataKeys",
              type: "bytes32[]",
            },
          ],
          name: "getDataBatchForTokenIds",
          outputs: [
            {
              internalType: "bytes[]",
              name: "dataValues",
              type: "bytes[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
          ],
          name: "getDataForTokenId",
          outputs: [
            {
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "getOperatorsOf",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "isOperatorFor",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_to",
              type: "address",
            },
          ],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "notify",
              type: "bool",
            },
            {
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "revokeOperator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          name: "setData",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "dataKeys",
              type: "bytes32[]",
            },
            {
              internalType: "bytes[]",
              name: "dataValues",
              type: "bytes[]",
            },
          ],
          name: "setDataBatch",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "tokenIds",
              type: "bytes32[]",
            },
            {
              internalType: "bytes32[]",
              name: "dataKeys",
              type: "bytes32[]",
            },
            {
              internalType: "bytes[]",
              name: "dataValues",
              type: "bytes[]",
            },
          ],
          name: "setDataBatchForTokenIds",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          name: "setDataForTokenId",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
          ],
          name: "tokenIdsOf",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "tokenOwnerOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "force",
              type: "bool",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "transfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "from",
              type: "address[]",
            },
            {
              internalType: "address[]",
              name: "to",
              type: "address[]",
            },
            {
              internalType: "bytes32[]",
              name: "tokenId",
              type: "bytes32[]",
            },
            {
              internalType: "bool[]",
              name: "force",
              type: "bool[]",
            },
            {
              internalType: "bytes[]",
              name: "data",
              type: "bytes[]",
            },
          ],
          name: "transferBatch",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
    YourContract: {
      address: "0x698D4840f1B68863e683A10d2006f6Fc826CaF82",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
