/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from '../utils/scaffold-eth/contract';

const externalContracts = {} as const;

export default externalContracts satisfies GenericContractsDeclaration;
